# Generated by Django 5.1.7 on 2025-03-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
